---
title: "Homework 0"
author: "Naveen Pednekar"
format: html
editor: visual
---

# 1

After assigning values to a, b, and c for $f(x) = ax^2+bx+c$, the quadratic formula is solved to give the solutions to $f(x)$. The solution(s) (or lack thereof) are printed below.

```{r}
#| echo: false
#| warning: false
a <- 1
b <- 3
c <- 2
solution1 <- (-b + sqrt(b^2 - 4*a*c)) / (2*a)
solution2 <- (-b - sqrt(b^2 - 4*a*c)) / (2*a)

if (is.nan(solution1) & is.nan(solution2)) {
  print("no real number solutions")
}

if (is.nan(solution1) & is.nan(solution2)==F) {
  print(solution2)
}

if (is.nan(solution1)==F & is.nan(solution2)) {
  print(solution1)
}

if (is.nan(solution1)==F & is.nan(solution2)==F & solution1 != solution2) {
  print(solution2)
  print(solution2)
}

if (is.nan(solution1)==F & is.nan(solution2)==F & solution1 == solution2) {
  print(solution1)
}
```

# 2

$f(x)$ is plotted below versus $x$ for $x \in (-5, 5)$. If there are solutions, the line $y=0$ can be seen.

```{r}
#| echo: false
x <- seq(-5, 5, length = 300)
plot(x, a*x^2 + b*x + c, type = "l")
abline(h=0, lty=2)
```
